Fix resolver.js example in README.md
The example must call `require("...").default(...)` instead of `require("...")(...)` otherwise an error is thrown:

```
TypeError: require(...) is not a function
```